### ISSUE TITLE
[NOMINATION]:+Year+and+Name

### ISSUE THREAD

**Issue by maximilien** [PQCA/governance#5]
# Nomination 🗳️

## Nominee Name
Michael Maximilien
@maximilien

## Short Personal Bio

Max (or Dr Max) is an IBM Distinguished Engineer and leader for the OSS teams contributing to all things open Quantum and Serverless.
Previously, Max was a principal engineer at IBM RTP for the worldwide point-of-sale standard: JavaPOS. Then at IBM Research-Almaden, he was a research scientist and did pioneering work on cloud computing and platform-as-a-service.
Max joined the IBM Cloud Labs in 2014 as Chief Architect for Cloud Innovations, leading IBM’s team for Cloud Foundry OSS then Knative/Kubernetes. As of 2024 Max rejoined IBM Research to help lead the quantum services, quantum open source, and quantum safe.
Max’s main expertise are in software engineering and distributed systems. Max published 100+ refereed papers with citations of 7500+ on GoogleScholar, 100s of blogs, and hold 21 issued patents. Max is an avid amateur photographer and triathlete; bragging rights: 2 award winning photos with Leica Society in 2021, 10 half Ironman, one full Ironman, and 20+ marathons.
Max has a master’s and PhD degrees in computer science and various executive certificates in AI and quantum.

## Short Personal Pitch
I can help steer the foundation into the first year and have the most background on its start and creation. Plus I have access to a wide ranging group of PQ researchers and developers.

**Comment by Naomi-Wash** [comment]
Results of the 2024 Post-Quantum Cryptography Alliance TAC Chairperson & Board Representative election. As there was only one nomination submitted, the nominee was automatically elected. 

Elected nominee: Michael Maximilien, IBM

The TAC mailing list has been notified.
